# Generated by Django 3.2.15 on 2023-06-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, unique=True, verbose_name='Название тэга')),
                ('color', models.TextField(blank=True, max_length=7, unique=True, verbose_name='Цвет в HEX')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Уникальная строка')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
    ]
