# Generated by Django 3.2.15 on 2023-05-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_new_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_password',
            field=models.CharField(blank=True, max_length=150, verbose_name='Пароль'),
        ),
    ]
