# Generated by Django 3.2.15 on 2023-05-27 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_current_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='new_password',
        ),
    ]
